

sass:
  sass_dir: assets/css

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap
 
title: "Dail Development Blog" # the name of your site, e.g. ACME Corp.
tagline: "A skill reset at its burtelest"
email: "lorenzo@vectorcr.com"
description: >- # this means to ignore newlines until "baseurl:"
author: Lorenzo Villalobos
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
google_analytics: UA-111111111-1
twitter:
  username: grievercr_0
  card: summary #keep this to generate a twitter share card
github_username:  vectorcr 
 
